version: 2.1
jobs:
  build:
    docker:
      - image: rastadidi/rfc4180-validator:latest
    steps:
      - checkout
      - run: echo "Pulling docker image... or do some compile/build/processing...generate files..."
  test-utf8:
    docker:
      - image: rastadidi/rfc4180-validator:latest
    steps:
      - checkout
      - run: echo "Testing UTF-8 encoding..."
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test-utf8
