version: 2.1
jobs:
  build:
    docker:
      - image: rastadidi/rfc4180-validator:latest
    steps:
      - checkout
      - run: echo "Pulling docker image... or do some compile/build/processing...generate files..."
  test-utf8:
    machine: true
    steps:
      - checkout
      - run: echo "Testing UTF-8 encoding..."
      - run: docker pull rastadidi/rfc4180-validator:latest
      - run: docker run -v ~/:/input rastadidi/rfc4180-validator
  test-csv:
    machine: true
    steps:
      - checkout
      - run: echo "Testing csv quality..."
      - run: docker pull rastadidi/rfc4180-validator:latest
      - run: docker run -v ~/:/input rastadidi/rfc4180-validator
  process:
    machine: true
    steps:
      - checkout
      - run: echo "Processing the datas..."      
workflows:
  version: 2
  test_and_process:
    jobs:
      - build
      - test-utf8
      - test-csv
      - process:
           requires:
             - build
